name: Update Powerball Data
on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install axios cheerio fs
      - name: Fetch latest Powerball data
        run: |
          node scrape.js
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add results.json || true
          git diff --quiet && echo "No changes" || (git commit -m "Update results" && git push)
